name: Qiskit-1.0.2
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.2=pyhd8ed1ab_0
  - ddt=1.7.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - fftw=3.3.10=hbd630f4_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gettext=0.21.0=hedfda30_2
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gobject-introspection=1.78.1=py38h42194e9_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - gtk2=2.24.33=h4ce724d_4
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - imagemagick=7.1.0_8=pl5321hb118871_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - jbig=2.1=hdba287a_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.8=h7f8727e_5
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - librsvg=2.56.3=hf6914bd_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_2
  - libtool=2.4.7=h6a678d5_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.37=h8459abe_0
  - nss=3.89.1=h6a678d5_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.18=hd6dcaed_0
  - pango=1.50.7=h668f713_2
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.46=hf426167_0
  - perl=5.32.1=0_h5eee18b_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h7934f7d_0
  - pkg-config=0.29.2=h1bed415_8
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.12=h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - alembic==1.14.1
      - amqp==5.3.1
      - annotated-types==0.7.0
      - anyio==4.5.2
      - async-timeout==5.0.1
      - backports-zoneinfo==0.2.1
      - billiard==4.2.1
      - blinker==1.8.2
      - celery==5.5.3
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - contourpy==1.1.1
      - cryptography==45.0.3
      - cycler==0.12.1
      - deprecation==2.1.0
      - dill==0.3.9
      - duet==0.2.8
      - ecdsa==0.19.1
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - flask==3.0.3
      - fonttools==4.56.0
      - greenlet==3.1.1
      - grpcio==1.70.0
      - grpcio-tools==1.70.0
      - h11==0.16.0
      - h5py==3.11.0
      - ibm-cloud-sdk-core==3.22.0
      - ibm-platform-services==0.59.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jose==1.0.0
      - jq==1.8.0
      - jwt==1.3.1
      - kiwisolver==1.4.7
      - kombu==5.5.4
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpi4py==4.1.1
      - mpmath==1.3.0
      - networkx==2.8.8
      - numpy==1.23.5
      - packaging==24.2
      - pandas==2.0.3
      - passlib==1.7.4
      - pbr==6.1.1
      - pika==1.3.2
      - pillow==10.4.0
      - protobuf==5.29.5
      - psutil==6.1.1
      - psycopg2-binary==2.9.10
      - pubchempy==1.0.4
      - pyasn1==0.4.8
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyjwt==2.9.0
      - pylatexenc==2.10
      - pyparsing==3.1.4
      - pyscf==2.8.0
      - pyspnego==0.11.2
      - python-dotenv==1.0.1
      - python-jose==3.4.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - qiskit==1.2.4
      - qiskit-aer==0.14.1
      - qiskit-algorithms==0.3.1
      - qiskit-ibm-provider==0.11.0
      - qiskit-ibm-runtime==0.34.0
      - qiskit-nature==0.7.2
      - qiskit-nature-pyscf==0.4.0
      - qulacs==0.6.11
      - redis==6.1.1
      - requests==2.32.3
      - requests-ntlm==1.3.0
      - rsa==4.9.1
      - rustworkx==0.15.1
      - scipy==1.10.1
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.41
      - starlette==0.44.0
      - stevedore==5.3.0
      - symengine==0.13.0
      - sympy==1.13.3
      - tenacity==9.0.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.2.3
      - uvicorn==0.33.0
      - vine==5.1.0
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/namrata.manglani.sakec/miniconda3/envs/Qiskit-1.0.2
